### PR TITLE
upgrade deps, vendorize, nits

### PR DESCRIPTION
**Pull request by pcarrier**
```
$ go get -u ./...
$ go mod tidy
$ go mod vendor
```

### CODE REVIEW

**Comment by creachadair** [comment]
I'm not sure what the rationale for vendoring may be here. I believe all the supported versions of Go handle modules at this point, right?

**Comment by pcarrier** [comment]
@creachadair AFAICT merely so that git clones are self-contained and nothing requires connectivity.

**Comment by creachadair** [comment]
> @creachadair AFAICT merely so that git clones are self-contained and nothing requires connectivity. Also allows projects to survive the disappearance of their dependencies.

I'm not convinced the overhead of cloning the dependencies is worthwhile in this case. None of the dependencies here is likely to go away (short of the Go project itself disappearing). I suppose my own `otp` library could disappear but I have no intention of doing that. 🙂

As for offline, if someone is too offline to even update from GitHub how will they sign in to the services that need the OTP values the tool generates?

Anyway, those are the reasons I would probably not bother with the vendoring step, but it's of course your call if you prefer that. 🙂

**Comment by pcarrier** [comment]
> As for offline, if someone is too offline to even update from GitHub how will they sign in to the services that need the OTP values the tool generates?

GitHub and other vendors can also go down… I've been impacted by GitHub outages too many times in my career to keep count.

**Pull request merged**
