### PR TITLE
Fix padding removal when decrypting a config file.

### LINKED ISSUE #32: Last line of SSL encrypted file decrypts incorrectly on win7/go.1.3
### Fixed in https://github.com/moshahmed/gauth/blob/gauth-vim-stdin-win7/gauth.go 

```
<     i := len(rest) - 1
<     for rest[i] < 16 {
---
>     i := len(rest)
>     for i>0 && rest[i-1] < 16 {

```

### LINKED ISSUE #35: Secrets are sometimes corrupted during decryption
In plain text, multiple line entries work
however, if you use  openssl enc -aes-128-cbc -md sha256 -in gauth.csv -out ~/.config/gauth.csv
the 2nd gauth pass number is invalid
Quick test. create two (2) opt entries, run the gauth and confirm on your mobile, encrypt and run again, the 1st entry is correct the 2nd is invalid

### PR DESCRIPTION
**Pull request by creachadair**
Fixes #35, fixes #18, fixes #32.

OpenSSL uses PKCS#5 padding, and the decryption code was not removing it
correctly. In some cases, this causes the last line of the decrypted config to
be mangled and produces invalid results.

To support this:

- Move config loading to gauth.LoadConfigFile.
- Inject a hook to read the user's password.
- Add unit tests that decryption doesn't corrupt the result.

### CODE REVIEW

**Comment by creachadair** [comment]
@pcarrier This change is larger than is strictly necessary, but I figured since I'm in here anyway I would do some other cleanup. If you would prefer a smaller change let me know and I will be glad to split this up.

**Comment by creachadair** [comment]
Hi, @pcarrier, when you have a moment could you please take a look? Thanks!

**Review by pcarrier — APPROVED** [review]
Thank you! Wanna drop old Go versions to fix CI?

**Comment by creachadair** [comment]
> Thank you, sorry I'm terrible at watching public GitHub notifications! Wanna drop old Go versions to fix CI?

Yes, I was going to propose that. I will update that file and fix the errors before merging.

**Comment by creachadair** [comment]
> > Thank you, sorry I'm terrible at watching public GitHub notifications! Wanna drop old Go versions to fix CI?
> 
> Yes, I was going to propose that. I will update that file and fix the errors before merging.

Would you be receptive to me switching this repo over to use GitHub Actions instead of Travis CI? I've found the performance of Actions to be faster and more consistent than Travis.

**Pull request merged**
