### PR TITLE
Add Docker support with Dockerfile

### PR DESCRIPTION
**Pull request by amcsi**
Cool project!

I helped Dockerize it for you.

You might want to also put it up on Docker Hub and add to the instructions how to just pull it from there.

### CODE REVIEW

**Comment by pcarrier** [comment]
Hi @amcsi, thanks for the contribution! Unfortunately I don't foresee spending any time doing release maintenance work on this. If you'd be interested, I'd be super curious to publishing Docker images through GitHub Actions.

**Comment by creachadair** [comment]
One question: Is there a use case for distributing `gauth` as a Docker image, as opposed to fetching a binary release from GitHub? Since a standalone Go binary does not have substantial runtime dependencies apart from libc, I would expect most uses to work fine with a linus/amd64 static build. Is there another context I'm overlooking?

**Comment by amcsi** [comment]
@creachadair I'm just so used to the bad side of Linux where nothing ever is as simple as executing a binary you download off the internet; you always have to rely on the application maintainer to release a package for your distro, or compile the binary yourself. And Docker's the best alternative to having to compile binaries yourself.

I just assumed Go is the same... is it not? If not, I didn't know that with Go and Linux you typically get binaries you can just run on any distro.

**Comment by creachadair** [comment]
I don't know if it holds for _every_ distribution, but certainly for Ubuntu, Debian, and Alpine, a binary built by `go build` should work fine without additional support. For example, I just did the following on my macOS machine:

```
mkdir -p ~/test
echo "Airbnb:abcd efgh ijkl mnop" > ~/test/gauth.csv
( cd gauth ; GOOS=linux GOARCH=amd64 go build -o ~/test/gauth .)
for dist in ubuntu debian alpine ; do
  docker run --rm -it -v ~/test:/test "$dist":latest sh -c 'GAUTH_CONFIG=/test/gauth.csv /test/gauth'
done
```

That is to say, a cross-compiled static binary of `gauth` for linux/amd64 works on all three of those distributions without modification.

That said: It's neither my place nor my intent to object to this change. It's only that Docker is a pretty heavyweight tool to throw at this problem. 🙂

**Comment by pcarrier** [comment]
Yes I think distributing static binaries would be complimentary and possibly more useful to more people, but I'm also not committing to work on either in the short term so whatever lands lands :)

**Comment by pcarrier** [comment]
Static binaries landed!

**Pull request closed without merging**
