### PR TITLE
Separate OTP generation into a library

### PR DESCRIPTION
**Pull request by creachadair**
No functional changes are intended; the main package now imports the library and uses it, but the implementation is unchanged.

Key points of note:
    
- Change the names of the functions to avert stutter, following the advice of Effective Go: https://golang.org/doc/effective_go.html#package-names
- Reorganize the helpers in main so control flow is easier to follow.    
- Add documentation comments.
- Add some very rudimentary unit tests.
- Add `go.mod` and `go.sum` files to support Go modules.

### CODE REVIEW

**Comment by creachadair** [comment]
As far as I can tell the CI failures are not triggered by this change (except insofar as maybe they haven't run in a while, and the un-vendored dependencies have changed).

**Comment by creachadair** [comment]
I wound up solving my problem another way. I'm going to close this PR to keep my dashboard clean, but if you'd like to reopen it later I'll be glad to help. Thanks for the tool!

**Comment by pcarrier** [comment]
@creachadair yes I'd be quite happy to merge if you'd like to reopen.

**Comment by creachadair** [comment]
I'll sort out the merge conflicts and update this shortly.

**Comment by creachadair** [comment]
Ok, I think the merge should be good now. I also fixed a couple of other lint-related issues.

**Comment by pcarrier** [comment]
Ha ha, please put quotes around Go versions, or 1.10 is interpreted as 1.1 (numerics)…

**Comment by creachadair** [comment]
Hm, in sorting out the merge I left kind of a messy history. If you'd like I can pre-squash that.

**Comment by creachadair** [comment]
All right, I unfscked the patch order and consolidated some of the local changes a bit. Sorry for the spammy thread here.

**Comment by pcarrier** [comment]
🙇

**Pull request merged**
